name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker logout
      run: docker logout
    - name: docker login
      run:
        docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Clean up unused images
      run: docker image prune -f
    - name: Build app image
      run: docker build . --file bld/prod/Dockerfile --tag app_prod
    - name: Tag app image
      run: docker tag app_prod ${{secrets.DOCKER_USER}}/osrs_investment_app:app_prod
    - name: Push app image
      run: docker push ${{secrets.DOCKER_USER}}/osrs_investment_app:app_prod